#!/bin/bash

#nghttp2
mkdir lib
cd lib
wget https://github.com/nghttp2/nghttp2/releases/download/v1.11.1/nghttp2-1.11.1.tar.gz
tar xzf nghttp2-1.11.1.tar.gz
cd nghttp2-1.11.1
apt-get install libssl-dev
export OPENSSL_CFLAGS='-I/usr/include/openssl'
export OPENSSL_LIBS='-L/usr/lib/x86_64-linux-gnu/ -lcrypto -lssl'
./configure
make
make install

